### PR TITLE
fix table text overlap

### PR DESCRIPTION
**Pull request by mikefortney**

### CODE REVIEW

**Review by kareemarab — APPROVED** [review]
preview looks good!

**Review by quick007 — CHANGES_REQUESTED** [review]
It would be better to use tailwind here, check out these docs: https://tailwindcss.com/docs/text-overflow#truncate

**Comment by mikefortney** [comment]
> It would be better to use tailwind here, check out these docs: https://tailwindcss.com/docs/text-overflow#truncate

I would but we are using react-data-table-component so we don't control the classes and have to override the styles...

**Comment by quick007** [comment]
```css
.dtable [data-tag="allowRowEvents"] {
  @apply !truncate;
  width: 100%;
}
```

**Pull request merged**
