### PR TITLE
Begin footer, add custom fonts

### PR DESCRIPTION
**Pull request by natclark**
Added "Red Rose" and "Open Sans". Using Google Fonts for now. Maybe we can self-host once license details are sorted.

### CODE REVIEW

**Comment by natclark** [comment]
Looks like vercel didn't like that :(

The "Deployment has failed link" is just a 404 for me

**Comment by kurdybacha** [comment]
could you try `yarn lint`, please?

**Comment by quick007** [comment]
I found this article pretty helpful with custom fonts and tw https://dev.to/thomasledoux1/the-best-way-to-use-google-fonts-in-next-js-tailwind-43a2

**Comment by mikefortney** [comment]
I was able to add the custom font in PR 17

**Comment by mikefortney** [comment]
@natclark can you please update or close this PR?

**Comment by natclark** [comment]
> I was able to add the custom font in PR 17

nice, closing now

**Pull request closed without merging**
