### PR TITLE
Add applicant detail page, more

### PR DESCRIPTION
**Pull request by mikefortney**
ditch swc compiler since it caused problems (feel free to change)
add prettier config
componentized pages
added most content for applicant page

### CODE REVIEW

**Comment by quick007** [comment]
any reason why you removed swc? What problems did you see?

**Comment by mikefortney** [comment]
I removed swc because it caused build fail locally, but I'm guessing babel is causing build fail on vercel...

**Comment by kurdybacha** [comment]
Looks great! Could you drop style changes only, please? It makes it easier for reviewers and let's me consistent with most opensource projects e.g. nextjs

**Comment by kurdybacha** [comment]
> Looks great! Could you drop style changes only, please? It makes it easier for reviewers and let's me consistent with most opensource projects e.g. nextjs

Ignore my comment about style. All good. But it looks you have some merge conflicts now. Could you resolve whenever you can, please?

**Pull request merged**
